name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # 2. Set up Docker Buildx (for multi-platform builds if needed)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    # Build all services using docker-compose
    - name: Build Docker Compose services
      run: |
        docker compose -f docker-compose.yml build --pull
